%YAML 1.2
---
-
    name: Prepare for system upgrade
    hosts: localhost
    remote_user: root

    tasks:
        -
            name: Create folder for packages.txt
            ansible.builtin.file:
                path: /usr/local/share/jasons-rhel-config/
                owner: root
                group: root
                mode: u=rx,g=,o=
                state: directory
        -
            name: Install file to be used by online-setup.sh
            ansible.builtin.copy:
                src: ../packages.txt
                dest: /usr/local/share/jasons-rhel-config/packages.txt
                owner: root
                group: root
                mode: u=r,g=,o=
        -
            name: Install second dependency of updates-phase-1.sh
            ansible.builtin.copy:
                src: ../online-setup.sh
                dest: /usr/local/bin/online-setup.sh
                owner: root
                group: root
                mode: u=rx,g=,o=
        -
            name: Install script for phase 1 of updates
            ansible.builtin.copy:
                src: ../updates-phase-1.sh
                dest: /usr/local/bin/updates-phase-1.sh
                owner: root
                group: root
                mode: u=rx,g=,o=
        -
            name: Install service for phase 1 of updates
            ansible.builtin.copy:
                src: ../updates-phase-1.service
                dest: /etc/systemd/system/updates-phase-1.service
                owner: root
                group: root
                mode: u=r,g=r,o=r
        -
            name: Install target for phase 1 of updates
            ansible.builtin.copy:
                src: ../updates-phase-1.target
                dest: /etc/systemd/system/updates-phase-1.target
                owner: root
                group: root
                mode: u=r,g=r,o=r
