%YAML 1.2
---
-
    name: Prepare for system upgrade
    hosts: localhost
    remote_user: root

    tasks:
        -
            name: Create folder for packages.txt
            ansible.builtin.file:
                path: /usr/local/share/jasons-rhel-config/
                owner: root
                group: root
                mode: u=rx,g=,o=
                state: directory
