%YAML 1.2
---
-
    name: Prepare for system upgrade
    hosts: localhost
    remote_user: root

    tasks:
        -
            name: Create folder for packages.txt
            ansible.builtin.file:
                path: /usr/local/share/jasons-rhel-config/
                owner: root
                group: root
                mode: u=rx,g=,o=
                state: directory
        -
            name: Install target for phase 1 of updates
            ansible.builtin.copy:
                src: ../updates-phase-1.target
                dest: /etc/systemd/system/updates-phase-1.target
                owner: root
                group: root
                mode: u=r,g=r,o=r
